@startuml Parent::ChiledA::GrandchildB
!include ./Parent.ChiledA.GrandchildB.GreatGrandchild.puml
class Parent::ChiledA::GrandchildB  {

}
Parent::ChiledA::GrandchildB +.. Parent::ChiledA::GrandchildB::GreatGrandchild
@enduml