@startuml SampleModel
!include ../../../SourceGeneratorTest.Library/SourceGeneratorTest/Library/Logs/ILogger.puml
!include ../../../SourceGeneratorTest.Library/SourceGeneratorTest/Library/Types/Parameters.puml
class SampleModel  {
    - <<readonly>> logger : ILogger
    + <<readonly>> Items : IDictionary<string, Item> <<get>>
    + SampleModel(logger : ILogger)
    + Write(writer : TextWriter) : void
    + <<async>> Execute(parameters : Parameters) : ValueTask
}
SampleModel *-- "*" "KeyValuePair`2" : Items
SampleModel ..> ILogger
SampleModel ..> TextWriter
SampleModel ..> Parameters
@enduml