@startuml SampleModel
class SampleModel  {
    - <<readonly>> logger : ILogger
    + <<readonly>> Items : IDictionary<string, Item> <<get>>
    + SampleModel(logger : ILogger)
    + Write(writer : TextWriter) : void
    + <<async>> Execute(parameters : Parameters) : ValueTask
}
SampleModel *-- "*" "KeyValuePair`2" : Items
SampleModel ..> TextWriter
@enduml