@startuml
class ClassDiagramGenerator {
    + ClassDiagramGenerator(writer:TextWriter, indent:string, ignoreMemberAccessibilities:Accessibilities, createAssociation:bool)
    + Generate(root:SyntaxNode) : void
    + GenerateInternal(root:SyntaxNode) : void
    + <<override>> VisitInterfaceDeclaration(node:InterfaceDeclarationSyntax) : void
    + <<override>> VisitClassDeclaration(node:ClassDeclarationSyntax) : void
    + <<override>> VisitStructDeclaration(node:StructDeclarationSyntax) : void
    + <<override>> VisitEnumDeclaration(node:EnumDeclarationSyntax) : void
    + <<override>> VisitConstructorDeclaration(node:ConstructorDeclarationSyntax) : void
    + <<override>> VisitFieldDeclaration(node:FieldDeclarationSyntax) : void
    + <<override>> VisitPropertyDeclaration(node:PropertyDeclarationSyntax) : void
    + <<override>> VisitMethodDeclaration(node:MethodDeclarationSyntax) : void
    + <<override>> VisitEnumMemberDeclaration(node:EnumMemberDeclarationSyntax) : void
    + <<override>> VisitEventFieldDeclaration(node:EventFieldDeclarationSyntax) : void
    + <<override>> VisitGenericName(node:GenericNameSyntax) : void
}
CSharpSyntaxWalker <|-- ClassDiagramGenerator
@enduml
