@startuml
class RelationshipCollection {
    + AddInheritanceFrom(syntax:TypeDeclarationSyntax) : void
    + AddInnerclassRelationFrom(node:SyntaxNode) : void
    + AddAssociationFrom(node:FieldDeclarationSyntax, field:VariableDeclaratorSyntax) : void
    + AddAssociationFrom(node:PropertyDeclarationSyntax) : void
    + GetEnumerator() : IEnumerator<Relationship>
    GetEnumerator() : IEnumerator
}
class "IEnumerable`1"<T> {
}
"IEnumerable`1" "<Relationship>" <|-- RelationshipCollection
@enduml
