@startuml
class Relationship {
    + Relationship(baseTypeName:TypeNameText, subTypeName:TypeNameText, symbol:string, baseLabel:string, subLabel:string)
    + <<override>> ToString() : string
}
@enduml
