@startuml
class Program {
    {static} Main(args:string[]) : int
}
enum OptionType {
    Value,
    Switch,
}
class "Dictionary`2"<T1,T2> {
}
Program o-> "options<string,OptionType>" "Dictionary`2"
Program +-- OptionType
@enduml
