@startuml
class Associations {
}
class AssociatedClass {
}
Associations o-> "ListOfA" AssociatedClass
Associations o-> "ListOfANullable" AssociatedClass
Associations o-> "CollectionOfA" AssociatedClass
Associations o-> "CollectionOfANullable" AssociatedClass
Associations o-> "IEnumarableOfA" AssociatedClass
Associations o-> "IEnumarableOfANullable" AssociatedClass
Associations o-> "ArrayOfA" AssociatedClass
Associations o-> "ArrayOfANullable" AssociatedClass
@enduml
