@startuml
class Parameters {
    + A : string <<get>> <<set>>
    + B : string <<get>> <<set>>
}
interface IItem {
}
class Item {
}
interface ILogger {
}
class MyClass {
    + ReadOnlyItems : IReadOnlyCollection<Item> <<get>>
    + Run(p:Parameters) : void
    + MyClass(logger:ILogger)
}
struct MyStruct {
    + MyStruct(p:Parameters)
}
class Settings {
}
class MyRecord <<record>> {
    + name : string <<get>> <<init>>
}
struct MyStructRecord <<record>> {
}
class ClassA {
    + ClassA(logger:ILogger)
}
MyClass o-- "0..*" Item : "Items"
MyClass "1" *-- "0..*" IItem : "ItemDictionary"
MyClass ..> Parameters : "use"
MyClass ..> ILogger : "Injection"
MyStruct o-- "0..*" int : "intCollection:List<int>"
MyRecord o-- Settings
MyStructRecord o-- "Name" string
ClassA --> "ILogger<ClassA>" : ""\escape	""
@enduml
