@startuml
class ClassA {
    - PropA : int <<get>>
    + PropB : int <<get>>
    # <<internal>> PropD : int <<get>>
    - MethodA() : void
}
class StructA <<struct>> {
    - PropA : string <<get>>
    {static} - PropB : string <<get>>
    {static} - MethodA() : void
}
@enduml
