@startuml
class ClassA {
    - PropA : int <<get>>
    + PropB : int <<get>>
    # <<internal>> PropD : int <<get>>
    - MethodA() : void
    - MethodB() : int
    + ClassA()
}
struct StructA {
    - PropA : string <<get>>
    {static} - PropB : string <<get>>
    - PropC : string <<get>>
    {static} - MethodA() : void
    - {static} MethodB() : int
    + StructA()
}
interface Interface {
    PropA : int <<get>>
    MethodA() : void
}
@enduml
