@startuml
class ClassA {
}
class ClassB {
}
interface IInterfaceA {
    Num2 : double <<get>>
}
interface IInterfaceB {
    Num2 : double <<get>>
}
class RecordA <<record>> {
    + Prop1 : string <<get>>
    + Prop2 : string <<get>>
    + RecordA(prop1:string, prop2:string)
}
class RecordB <<record>> {
    + Prop1 : string <<get>>
    + Prop2 : string <<get>>
    + RecordB(prop1:string, prop2:string)
}
class StructA <<struct>> {
    + StructA(field1:RecordA)
}
class StructB <<struct>> {
    + StructB(field1:RecordB)
}
class RecordStructA <<record>> <<struct>> {
    + X : int <<get>> <<init>>
    + Y : int <<get>> <<init>>
}
class RecordStructB <<record>> <<struct>> {
    + X : int <<get>> <<init>>
    + Y : int <<get>> <<init>>
}
enum EnumA {
    A,
    B,
    C,
}
enum EnumB {
    A,
    B,
    C,
}
StructA --> "field1" RecordA
StructA --> RecordA : "use"
StructB --> "field1" RecordB
StructB --> RecordB : "use"
@enduml
