class ClassA {
    # X : double = 0
    # Y : double = 1
    # Z : double = 2
    # PropA : int <<get>>
    # <<internal>> PropB : string <<get>> <<protected set>>
    <<internal>> PropC : double <<get>> = 3.141592
    + PropD : string <<get>>
    + ClassA()
    {static} ClassA()
    # <<virtual>> VirtualMethod() : void
    + <<override>> ToString() : string
    + {static} StaticMethod() : string
    + ExpressonBodiedMethod(x:int) : void
}
abstract class ClassB {
    + {abstract} PropA : int <<get>> <<protected set>>
    # <<virtual>> VirtualMethod() : string
    + {abstract} AbstractMethod(arg1:int, arg2:double) : string
}
class ClassC <<sealed>> {
    + <<override>> PropA : int <<get>> <<protected set>> = 100
    +  <<event>> PropertyChanged : PropertyChangedEventHandler 
    + <<override>> AbstractMethod(arg1:int, arg2:double) : string
    # <<override>> VirtualMethod() : string
}
class Vector <<struct>> {
    + X : double <<get>>
    + Y : double <<get>>
    + Z : double <<get>>
    + Vector(x:double, y:double, z:double)
    + Vector(source:Vector)
}
enum EnumA {
    AA= 0x0001,
    BB= 0x0002,
    CC= 0x0004,
    DD= 0x0008,
    EE= 0x0010,
}
class NestedClass {
    + A : int <<get>>
}
class "IList`1"<T> {
}
class InnerClass {
    + X : string <<get>> = "xx"
    + MethodX() : void
}
class InnerStruct <<struct>> {
    + A : int <<get>>
    + InnerStruct(a:int)
}
ClassB --> "publicA" ClassA
ClassB o-> "listOfA<ClassA>" "IList`1"
ClassB <|-- ClassC
INotifyPropertyChanged <|-- ClassC
ClassC --> "PropB" ClassB
NestedClass --> "B" InnerClass
NestedClass +-- InnerClass
InnerClass +-- InnerStruct
